# Generated by Django 5.1.4 on 2025-01-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
