# Generated by Django 5.1.4 on 2024-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='cars/'),
        ),
    ]
